### ISSUE TITLE
Ajouter un favicon spécifique à l'application

### ISSUE THREAD

**Issue by kosssi** [CPatchane/create-cozy-app#1140]
Le but de cette issue est de se souvenir que l'on peut améliorer la gestion des favicons pour les prochaines applications.

A faire:
- Ajouter un png avec le logo de l'application (le créateur de l'app aurait juste à changer ce PNG)
- Créer des commandes pour générer toutes les favicons depuis ce PNG

Tu en penses quoi @CPatchane ?

Cette issue fait référence à https://github.com/CPatchane/create-cozy-app/pull/1139 qui permet d'afficher le favicon de la stack.

**Comment by CPatchane** [comment]
The next major version of cozy-scripts will handle automatically the favicon using the `.svg` file used by the application in its `manifest.webapp`. Did the PR #1069 resolves your issue here?
For now, I still don't see the link between this issue and #1139 which is about using a stack variable for the stack favicon, I may need more context, I asked some questions in this related PR.

**Comment by CPatchane** [comment]
The #1139 is now closed, should we close this issue as well @kosssi ?

**Comment by CPatchane** [comment]
Any news @kosssi ?

**Comment by kosssi** [comment]
yes it's resolves this issue 👍
