### ISSUE TITLE
hook for prettier and eslint

### ISSUE THREAD

**Issue by enguerran** [CPatchane/create-cozy-app#205]
When developing a project with `prettier`, I write code without bothering me about formating lines. I write, and focus on the plus-value I add to the project.
If developers don't have a well configured editor that runs `prettier --write '{src,test}/**/*.{js,jsx}' && eslint --fix '{src,test}/**/*.{js,jsx}'` on each modified file, we will have a very inconsistent code base. I think it is very useful to add a git hook that runs `prettier --write '{src,test}/**/*.{js,jsx}' && eslint --fix '{src,test}/**/*.{js,jsx}'` on every commit.

And also, it is hard to know which rules are behind elsint `"extends": ["cozy-app"]`, I guess there is no formating rules, because running `prettier --write '{src,test}/**/*.{js,jsx}' && eslint --fix '{src,test}/**/*.{js,jsx}'` will render `prettier` useless.

**Comment by CPatchane** [comment]
Thanks @enguerran for this issue. I see your point but I don't want to command this usage to all developers. The prettier npm script is available in the `package.json` and usable by the developer like he wants.
And for now, since the eslint-config cozy-app is based on `standardjs`, this command allows to keep the both working together (`standardjs` for rules and `prettier` as formatter). Again here, the developper can get rid of this to use `prettier` only. But at least the choice is suggested.
I close this issue for now, I will reopen if there are new comments on it.
