### ISSUE TITLE
Simplify npm scripts

### ISSUE THREAD

**Issue by enguerran** [CPatchane/create-cozy-app#207]
As a developer I don't know where to start.
For instance, `build` scripts (https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/template/package.json#L12-L15):
```json
"build": "yarn run build:browser",
"commons:build": "cozy-scripts build",
"build:browser": "NODE_ENV=browser:production npm-run-all --serial clean:browser lint:js tx commons:build",
"build:mobile": "NODE_ENV=mobile:production npm-run-all --serial clean:mobile lint:js tx commons:build",
```

### First: `build:mobile` vs `build:browser`.

Both are the same but for `NODE_ENV` variable and for the `clean` script. We may make the `clean` script depend on the `NODE_ENV` to do what it does. Then we'll have:
```json
"build:browser": "NODE_ENV=browser:production npm-run-all --serial clean lint:js tx commons:build",
"build:mobile": "NODE_ENV=mobile:production npm-run-all --serial clean lint:js tx commons:build",
```

### Second: use  **prescript**, **script**, **postscript** npm builtin workflow.

The real build task is owned by `cozy-scripts`, `clean`, `lint`, `tx` tasks are prebuild tasks:
```json
"build": "cozy-scripts build",
"prebuild": "npm-run-all --serial clean lint:js tx",
"build:browser": "NODE_ENV=browser:production npm run build" 
"build:mobile": "NODE_ENV=mobile:production npm run build",
```
### Third: do the exact same reasoning for every linked-with-each-other scripts.

- build
- watch
- etc.

### Fourth: limit 0 config scripts to the very minimum

To ease first step, `scripts` object must contain a really short scripts list:

- test
- watch (or start)
- build
- deploy

Targets (mobile, browser) must be controlled by a flag or environment variable.

**Comment by CPatchane** [comment]
Thanks @enguerran for this issue. 
First of all, I agree that the scripts list can be a little impressive at a first sight. But, at least, all available scripts are here and presented to the developer who is finally free to clean or not and keep the scripts that he really wants.

> __First: build:mobile vs build:browser__

I agree, but if I understand correctly your example I will just get rid of one line while adding more logic in a global clean script. I personally don't see the added value here (nothing more explicit and clearer than a `rm -rf build/*` IMHO).

> __Second: use prescript, script, postscript npm builtin workflow.__
> __Third: do the exact same reasoning for every linked-with-each-other scripts.__

We used these kind of scripts in previous Cozy applications and the number of scripts is globally the same. If I compare the equivalent build script:

```json
"build": "cozy-scripts build",
"prebuild": "npm-run-all --serial clean lint:js tx",
"build:browser": "NODE_ENV=browser:production npm run build" 
"build:mobile": "NODE_ENV=mobile:production npm run build",
```

```json
"build": "yarn run build:browser",
"commons:build": "cozy-scripts build",
"build:browser": "NODE_ENV=browser:production npm-run-all --serial clean lint:js tx commons:build",
"build:mobile": "NODE_ENV=mobile:production npm-run-all --serial clean lint:js tx commons:build",
```

I clearly prefer the second way which is clearly more explicit because nothing is done under the hood by npm or yarn. Also in your example, running the simple `build` script will only build the application without the previous scripts (which is unwanted) instead of being a shortcut to `build:browser` (which is useful IMHO).
By the way, since this is specific to NPM, these scripts seems to work (at the time when I tested) only if you use the `npm` command and not using `yarn` in the script like in my example just above.

> Targets (mobile, browser) must be controlled by a flag or environment variable.

Actually, it's already the case, the environment and target are specified to the script using the `NODE_ENV` environment variable. All scripts (build, watch, test, config) is done using one script and the specifier (`:browser`, `:development`, ...) allow to define these variables without to be known by the developer each time he wants to use theme while avoiding mistakes. So I don't see your point here :/

**Comment by enguerran** [comment]
I knew you would disagree: you did this way for the exact same reasons you disagree this issue.
Nevertheless, as an end-user, I found the first steps very intricate and I suggested all of these to ease the first step for new developers that would like to create a new cozy app in seconds.

I think KISS is a good reference and this talk is very inspiring
https://www.infoq.com/presentations/Simple-Made-Easy

**Comment by CPatchane** [comment]
I'll try to keep that in mind. Thanks for the point and the link @enguerran 👍
