### ISSUE TITLE
npm run config and enhance webpack config with particular needs

### ISSUE THREAD

**Issue by enguerran** [CPatchane/create-cozy-app#211]
The script `npm run config` do not expose the complete webpack configuration.

I tried to do
```
npm run config > app.config.js
```
but webpack don't run with this "compiled" config file.

BTW: why do you change webpack config file name?

**Comment by CPatchane** [comment]
I didn't change the webpack config file name because it's not what you think it is. The `app.config.js` should only export a list of webpack configuration objects as it's already explained in the [documentation](https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/docs/webpack-configs.md#webpackbundledefaultjs) (to improve and must be more visible I know).
The only thing you have to do here is to make a specific `cozy-client` config file (which could be added to CCA in the future when `cozy-client` will be more mature) and use it like this:

```js
// app.config.js

module.exports = [
  require('cozy-scripts/config/webpack.bundle.default'),
  require('./config/cozyClient.config.js')
]
```

And that's it, you don't need `webpack-merge` here since `cozy-scripts` will already read these objects and merge them to get the final webpack configuration.
I know it's a little complicated at a first sight but that will allow to keep the configuration opinionated if a developer only need the `bundle.default` while providing a way to overload or rewrite the configuration for other needs.
